version: '3'
networks:
  dbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.2/0
services:
  student_service:
    image: jaborvs/student_service:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"
    networks:
      - dbnet
  mongo:
    restart: unless-stopped
    image: mongo:4
    ports:
      - "27017:27017"
    networks:
      - dbnet